version: 2.1

jobs:
  deploy:
    docker:
      - image: circleci/php:7.4-apache-node
    steps:
      - checkout

      # Cache Composer dependencies
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "src/composer.lock" }}
            - composer-v1-

      - run:
          name: Install Composer Dependencies
          command: cd src && composer install --no-interaction --prefer-dist

      - save_cache:
          paths:
            - src/vendor
          key: composer-v1-{{ checksum "src/composer.lock" }}

      # Install Vercel CLI Locally in the src directory
      - run:
          name: Install Vercel CLI Locally
          command: cd src && npm install vercel

      - run:
          name: Deploy to Vercel
          command: |
            cd src
            if [ "$CIRCLE_BRANCH" == "main" ] || [ "$CIRCLE_BRANCH" == "master" ]; then
              npx vercel --prod . --yes --token $VERCEL_TOKEN \
              --env VERCEL_PROJECT_ID=$VERCEL_PROJECT_ID \
              --env VERCEL_ORG_ID=$VERCEL_ORG_ID
            elif [ "$CIRCLE_BRANCH" == "dev" ]; then
              npx vercel dev . --yes --token $VERCEL_TOKEN \
              --env VERCEL_PROJECT_ID=$VERCEL_PROJECT_ID \
              --env VERCEL_ORG_ID=$VERCEL_ORG_ID
            elif [ "$CIRCLE_BRANCH" == "preview" ]; then
              npx vercel . --yes --token $VERCEL_TOKEN \
              --env VERCEL_PROJECT_ID=$VERCEL_PROJECT_ID \
              --env VERCEL_ORG_ID=$VERCEL_ORG_ID
            fi

workflows:
  version: 2
  deploy:
    jobs:
      - deploy
