version: 2.1

jobs:
  deploy:
    docker:
      - image: circleci/php:7.4-apache-node
    steps:
      - checkout
      - run:
          name: Install Composer Dependencies
          command: cd src && composer install
      - run:
          name: Install Vercel CLI Locally
          command: npm install vercel
      - run:
          name: Deploy to Vercel
          command: |
            if [ "$CIRCLE_BRANCH" == "main" ] || [ "$CIRCLE_BRANCH" == "master" ]; then
              npx vercel --prod src --yes --token $VERCEL_TOKEN \
              --env VERCEL_PROJECT_ID=$VERCEL_PROJECT_ID \
              --env VERCEL_ORG_ID=$VERCEL_ORG_ID
            elif [ "$CIRCLE_BRANCH" == "dev" ]; then
              npx vercel dev src --yes --token $VERCEL_TOKEN \
              --env VERCEL_PROJECT_ID=$VERCEL_PROJECT_ID \
              --env VERCEL_ORG_ID=$VERCEL_ORG_ID
            elif [ "$CIRCLE_BRANCH" == "preview" ]; then
              npx vercel src --yes --token $VERCEL_TOKEN \
              --env VERCEL_PROJECT_ID=$VERCEL_PROJECT_ID \
              --env VERCEL_ORG_ID=$VERCEL_ORG_ID
            fi

workflows:
  version: 2
  deploy:
    jobs:
      - deploy
